### ISSUE TITLE
Cargo.lock in repo

### ISSUE THREAD

**Issue by Moredread** [miosta/pacgirl#1]
Hey,

isn't the Cargo.lock a file that shouldn't be versioned?

**Comment by aepsil0n** [comment]
afaik this only applies to crates, not executables.

**Comment by Moredread** [comment]
http://doc.crates.io/guide.html#cargo.toml-vs-cargo.lock Jupp... I don't know if I really like that, but if this is consens...

**Comment by aepsil0n** [comment]
Well, it does make sure, the build does not accidentally break, when upstream crates violate semantic versioning. They should not do that to begin with, but you never know…
